### ISSUE TITLE
nextcloud Let's encrypt not working after running #573

### ISSUE THREAD

**Issue by tip0x** [nextcloud-snap/nextcloud-snap#2178] opened 2022-09-15 07:04 UTC
Attempting to obtain certificates... error running certbot:

An unexpected error occurred:
IOError: [Errno 13] Permission denied: '/etc/os-release'
Please see the logfile '/tmp/tmpBWzO2f' for more details.
[](url)
![#573](https://user-images.githubusercontent.com/112777779/190337060-1aef1a86-899c-44bf-b18e-b722389e4d39.png)

**Comment by tip0x** [comment] 2022-09-16 00:36
I ran the script `$ sudo snap refresh nextcloud --channel=beta/pr-573` and it returned `snap "nextcloud" has no updates available`.
Yes I am using pop OS.
and I don't seem to trace `/etc/letsencrypt/cli.ini` in my directory.

**Comment by kyrofa** [comment] 2022-09-16 15:37
I'm afraid that this is a dupe of #1348, then, which is due to [LP: #1881189](https://bugs.launchpad.net/snapd/+bug/1881189) in snapd. There's nothing we can do to properly support pop os.

**Closed by kyrofa** 2022-09-16 15:37 UTC
