### ISSUE TITLE
Snap 29 issues

### ISSUE THREAD

**Issue by Halokk424** [nextcloud-snap/nextcloud-snap#2818] opened 2024-07-15 19:23 UTC
Can anyone please help me by enabling the OpenOffice or nextcloud office to the latest  snap running on 29.0.2,?
Tried using the app ones but still out of luck.

Also how can I enable thumbnails on  mov, mp4, docx type documents? I tried preview generator but it doesn't do anything

Sorry but I'm a newcomer and still learning Linux. Any step by step tutorial  to follow will be great

Thank you

**Comment by scubamuc** [comment] 2024-07-15 20:11
Hey @Halokk424 welcome and thanks for your request.
>Can anyone please help me by enabling the OpenOffice or nextcloud office to the latest snap running on 29.0.2,?

sure, see [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)

>Sorry but I'm a newcomer and still learning Linux. Any step by step tutorial to follow will be great

Its great that you're eager and willing to learn Linux. We're all FOSS people here and we love open source software. Welcome to a fantastic community! We'll not be able to tutor you in Linux or give you step by step instructions though. There are plenty videos and guides out there to get you started. For learning Linux I personally recommend https://www.learnlinux.tv/, Jay makes great videos.

We're glad to assist if you have issues with Nextcloud snap. But you'll need to do some research and be very clear about your issues. 

See our [Nextcloud snap Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki)
See our [Nextcloud snap FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's)
See [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

>Also how can I enable thumbnails on mov, mp4, docx type documents? I tried preview generator but it doesn't do anything

For general Nextcloud issues the [Nextcloud Community Forum](https://help.nextcloud.com/) is the place to go.

Have fun, stay at it, do the basics and read read read the docs...

**Comment by Halokk424** [comment] 2024-07-16 02:46
thank you for returning back to me , really appreciate it.

I have tried installed the Collabora Online - Built-in CODE Server (ARM64) and activate it after performing all the steps from the website you provided but all i get was an error 
![aaaa](https://github.com/user-attachments/assets/7fa6dabf-5b9a-42eb-aca9-e918236b0ed2)

literally stuck here and no clue.

nextcloud snap is running perfectly fine as of now all lacking was the office intergration and the lack of preview thumbnails.
I really love this project and want to say a big THANK YOU for those who made this for the community !

Regards,
Kei

**Comment by scubamuc** [comment] 2024-07-16 05:50
Hey @Halokk424,
>thank you for returning back to me , really appreciate it.

you're welcome.

>I have tried installed the Collabora Online - Built-in CODE Server (ARM64) and activate it after performing all the steps from the website you provided but all i get was an error

well done! 

did you see this note at the end of the wiki topic?

![grafik](https://github.com/user-attachments/assets/c9c38bdd-5dde-430e-89b1-587d7e2abcb9)

this seems to be a [third party app](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do) issue.

**Comment by scubamuc** [comment] 2024-07-16 06:58
Hey @Halokk424, 

>Also how can I enable thumbnails on mov, mp4, docx type documents? I tried preview generator but it doesn't do anything

your issues concerning the missing previews seems to be an upstream issue with [requests coming in since 29.0.2](https://help.nextcloud.com/)... it looks like this may be [fixed in 29.0.4](https://help.nextcloud.com/t/rc1s-of-28-0-8-and-29-0-4/197921) which is due sometime next week...

I can't confirm this issue on my 29.02 instance though, this is what I'm seeing:
![grafik](https://github.com/user-attachments/assets/3484f7fa-c7e9-46db-8d41-03bd19a804e1)
![grafik](https://github.com/user-attachments/assets/9bb4f727-8b03-4e91-872e-662306583e81)

so you'll have to be patient and wait for your thumbnails to appear again 🤿

**Comment by scubamuc** [comment] 2024-07-16 07:54
@Halokk424,

see https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/ to install OnlyOffice until the ARM64 CODE issue is solved... maybe that will work for you?

please close here if you're happy

**Comment by Halokk424** [comment] 2024-07-16 09:25
thank you for all the supportive advices.
so both issue cant be fixed at this stage am i correct?
nothing can be done to make them work again?

Regards,
Kei

**Comment by scubamuc** [comment] 2024-07-16 11:01
@Halokk424 
>nothing can be done to make them work again?

that is correct. none of these issues are within our realm, see https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-why-is-nextcloud-snap-version-out-of-sync-with-upstream-nextcloud

**Comment by pachulo** [comment] 2024-07-16 15:56
> Also how can I enable thumbnails on mov, mp4, docx type documents?

For the video files you should be able to apply the workaround mentioned [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/1327), till I have some time to implement something more snap-native 😓

**Comment by scubamuc** [comment] 2024-07-16 16:11
@pachulo, can you please check that command:
![grafik](https://github.com/user-attachments/assets/fc5dded7-6bf0-4acf-b5cd-57c4f437c145)
that doesn't seem to be correct

these are the available options in the helpfile
![grafik](https://github.com/user-attachments/assets/a0fb6d53-672d-473b-aa77-46962807c1f1)

**Comment by Halokk424** [comment] 2024-07-20 08:27
Thank you for all the advices. Really appreciate it.
One more question. How do i edit the cron job like i would like to add an exist command for preview generation for cron. How do i access the php file to edit it?

**Comment by Halokk424** [comment] 2024-07-20 08:28
i would like to add this to cron job for my nextcloud instances.
sudo nextcloud.occ preview:generate-all -vvv

**Comment by scubamuc** [comment] 2024-07-20 09:36
Hey @Halokk424, 

>How do i access the php file to edit it?

this is not possible in the snap

>i would like to add this to cron job for my nextcloud instances.

you want to add a cron job as root on the host running the snap;

view root crontab on Linux `sudo crontab -l`
edit root crontab on Linux `sudo crontab-e` 
add root cronjob as **root** `* * * * * nextcloud.occ preview:generate-all -vvv` 
add root cronjob as **user** `* * * * * su <USER> /home/<USER>/path/to/script.sh` 
see  https://crontab.guru/ for required schedule expression
please close here if you are d'accord.

**Closed** 2024-07-22 06:50 UTC

**Comment by scubamuc** [comment] 2024-08-15 06:45
> > Also how can I enable thumbnails on mov, mp4, docx type documents?
> 
> @Halokk424 for the video files you should be able to apply the workaround mentioned [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/1327), till I have some time to implement something more snap-native 😓

@pachulo, this causes issues... see [workaround preview generator app](https://github.com/nextcloud-snap/nextcloud-snap/wiki/workaround-preview-generator#known-issues-preview-generator-app)! See [Nextcloud issues](https://help.nextcloud.com/t/nextcloud-creating-never-ending-mysql-threads/157752)... [cleaning up](https://github.com/nextcloud-snap/nextcloud-snap/wiki/database%E2%80%90apps%E2%80%90files%E2%80%90maintenance#database-apps-and-files-maintenance) the mess is a chore!

@pachulo I'd like to suggest not pointing to that workaround?

**Comment by pachulo** [comment] 2024-10-14 22:08
> @pachulo, this causes issues... see [workaround preview generator app](https://github.com/nextcloud-snap/nextcloud-snap/wiki/workaround-preview-generator#known-issues-preview-generator-app)! See [Nextcloud issues](https://help.nextcloud.com/t/nextcloud-creating-never-ending-mysql-threads/157752)... [cleaning up](https://github.com/nextcloud-snap/nextcloud-snap/wiki/database%E2%80%90apps%E2%80%90files%E2%80%90maintenance#database-apps-and-files-maintenance) the mess is a chore! Suggest not pointing to that workaround?

As you say [here](https://help.nextcloud.com/t/nextcloud-creating-never-ending-mysql-threads/157752/4), I think that the problem is _the combination_ of preview generator + external files, not preview generator itself.
