### ISSUE TITLE
Sudden slowdown in login and logoff processes

### ISSUE THREAD

**Issue by dln949** [nextcloud-snap/nextcloud-snap#2652] opened 2024-01-18 01:27 UTC
Starting just a few days ago, when logging in to my Nextcloud server from a web browser, the log in process has degraded, and instead of taking the usual 5 - 10 seconds now drags on for almost one full minute.  Likewise with the process of logging off.  But, while logged into the Nextcloud server, everything is as snappy as ever.  I can't figure out why the process of logging in and off now takes so long.  

Nextcloud 27.1.4snap1

main59@system59:~$ snap version
snap    2.61.1
snapd   2.61.1
series  16
ubuntu  22.04
kernel  6.5.0-14-generic

I've attached the requested logs in a text file.  

[NextcloudOutput.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13971038/NextcloudOutput.txt)

**Comment by scubamuc** [comment] 2024-01-18 07:22
your `php-fpm` logs are showing:
```
[17-Jan-2024 14:04:33] WARNING: [pool www] child 2980993 exited on signal 9 (SIGKILL) after 21.669029 seconds from start
[17-Jan-2024 14:04:33] NOTICE: [pool www] child 2981234 started
[17-Jan-2024 14:04:52] WARNING: [pool www] child 2981234 exited on signal 9 (SIGKILL) after 18.846630 seconds from start
[17-Jan-2024 14:04:52] NOTICE: [pool www] child 2981320 started
[17-Jan-2024 14:05:05] WARNING: [pool www] child 2980985 exited on signal 9 (SIGKILL) after 60.558138 seconds from start
[17-Jan-2024 14:05:05] NOTICE: [pool www] child 2981473 started
[17-Jan-2024 14:05:14] WARNING: [pool www] child 2981236 exited on signal 9 (SIGKILL) after 39.653136 seconds from start
[17-Jan-2024 14:05:14] NOTICE: [pool www] child 2981521 started
[17-Jan-2024 14:05:18] WARNING: [pool www] child 2981238 exited on signal 9 (SIGKILL) after 43.592811 seconds from start
[17-Jan-2024 14:05:18] NOTICE: [pool www] child 2981526 started
[17-Jan-2024 14:05:20] WARNING: [pool www] child 2981320 exited on signal 9 (SIGKILL) after 27.829470 seconds from start
[17-Jan-2024 14:05:20] NOTICE: [pool www] child 2981529 started
[17-Jan-2024 14:05:32] WARNING: [pool www] child 2981473 exited on signal 9 (SIGKILL) after 27.055663 seconds from start
[17-Jan-2024 14:05:32] NOTICE: [pool www] child 2981545 started
[17-Jan-2024 14:05:34] WARNING: [pool www] child 2981521 exited on signal 9 (SIGKILL) after 20.034957 seconds from start
[17-Jan-2024 14:05:34] NOTICE: [pool www] child 2981548 started
[17-Jan-2024 14:05:46] WARNING: [pool www] child 2981526 exited on signal 9 (SIGKILL) after 28.040321 seconds from start
[17-Jan-2024 14:05:46] NOTICE: [pool www] child 2981566 started
[17-Jan-2024 14:05:48] WARNING: [pool www] child 2981529 exited on signal 9 (SIGKILL) after 27.977361 seconds from start
[17-Jan-2024 14:05:48] NOTICE: [pool www] child 2981569 started
[17-Jan-2024 14:09:31] WARNING: [pool www] child 2994647 exited on signal 9 (SIGKILL) after 29.163960 seconds from start
[17-Jan-2024 14:09:31] NOTICE: [pool www] child 2994859 started
```
which is probably what is taking so long when logging in.

can you recall any changes made to your system, maybe network changes... like proxy setting? because these logs `apache` logs are showing network issues:
```
[Wed Jan 17 14:17:21.776786 2024] [proxy:error] [pid 2260240:tid 140054340544256] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /tmp/sockets/php-fpm.sock (*:80) failed
[Wed Jan 17 14:17:25.048864 2024] [proxy_fcgi:error] [pid 2260240:tid 140054340544256] [client 154.47.25.130:48146] AH01079: failed to make connection to backend: httpd-UDS
[Wed Jan 17 14:17:21.746311 2024] [proxy:error] [pid 2260384:tid 140054211045120] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /tmp/sockets/php-fpm.sock (*:80) failed
[Wed Jan 17 14:17:21.760933 2024] [proxy:error] [pid 2260240:tid 140053514811136] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /tmp/sockets/php-fpm.sock (*:80) failed
[Wed Jan 17 14:17:25.049095 2024] [proxy_fcgi:error] [pid 2260384:tid 140054211045120] [client 154.47.25.130:11328] AH01079: failed to make connection to backend: httpd-UDS
```

**Comment by scubamuc** [comment] 2024-01-18 07:26
I stand to be corrected, but even though you issue is clear from your description and can be confirmed in your logs, this is most probably not a Nextcloud snap issue.

**Comment by dln949** [comment] 2024-01-18 07:26
Thanks.  

Sorry, no, but I can't think of any such changes.  (I wouldn't even know how to make a change to a "proxy setting", partly because I don't even know what that is.)  

I don't understand what the messages you selected are telling us.

**Comment by scubamuc** [comment] 2024-01-18 07:36
can you give us some details about you system and your setup?

your news app is full of errors. that concerns mainly unreachable news sites which could point to a network connection issue. .. or its just miss-configured. do you use the news app regularly? are there any errors displayed in the client?

**Comment by dln949** [comment] 2024-01-18 07:41
I very seldom use the news app within Nextcloud itself, instead I use it as the central repository that I access via an android client ("News") and via a desktop computer client ("NewsFlash").  It is very possible that some of the news sites are no longer valid URLs, depending on what I'm being asked to monitor I add various sites but then I don't keep following them so I've never attempted to clean them up.  Maybe I should do that????  (Although I will say that I don't think this is a recent issue.)

**Comment by scubamuc** [comment] 2024-01-18 07:50
Yeah, I agree. There are no timestamps in the news error logs anyhow.

We'll need to know some system details though.

**Comment by dln949** [comment] 2024-01-18 08:12
Architecture:  x86_64
I have the Nextcloud snap installed on a separate computer I own at my location.  I guess it is "internet facing" since I can access remotely over the internet.

**Comment by scubamuc** [comment] 2024-01-18 08:17
> Architecture: x86_64
I have the Nextcloud snap installed on a separate computer I own at my location. I guess it is "internet facing" since I can access remotely over the internet.

thanks, that'll do
I have no idea why your system is having those `php-fpm` issues, so lets wait and see if our devs can shed some light...

**Comment by scubamuc** [comment] 2024-01-25 10:32
@kyrofa any ideas?

**Comment by scubamuc** [comment] 2024-02-15 11:52
this is not a bug, but a security feature in managed by [Brute-force protection](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html). when three consecutive logins have failed, Nextcloud will slow down Login with a wait of 30+ seconds depending on settings.

this is certainly not a snap issue

so I'll go ahead and close this issue then

**Closed by scubamuc** 2024-02-15 11:52 UTC
Labels: help wanted
