### ISSUE TITLE
GuzzleHttp\Exception\ConnectException

### ISSUE THREAD

**Issue by MaximePou** [nextcloud-snap/nextcloud-snap#2353] opened 2023-03-14 10:30 UTC
#### Describe the bug

My nextcloud server stops responding for several seconds

I have this error

[richdocuments] Erreur: GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 45001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://cloud.yvetot.fr/extra-apps/richdocumentscode/proxy.php?req=/hosting/capabilities at <<closure>>

 0. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 158
    GuzzleHttp\Handler\CurlFactory::createRejection()
 1. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 110
    GuzzleHttp\Handler\CurlFactory::finishError()
 2. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 47
    GuzzleHttp\Handler\CurlFactory::finish()
 3. /snap/nextcloud/33908/htdocs/lib/private/Http/Client/DnsPinMiddleware.php line 113
    GuzzleHttp\Handler\CurlHandler->__invoke()
 4. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 35
    OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensitive parameters replaced ***")
 5. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 31
    GuzzleHttp\PrepareBodyMiddleware->__invoke()
 6. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 7. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 63
    GuzzleHttp\RedirectMiddleware->__invoke()
 8. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 75
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 9. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 331
    GuzzleHttp\HandlerStack->__invoke()
10. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 168
    GuzzleHttp\Client->transfer()
11. /snap/nextcloud/33908/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Client->requestAsync()
12. /snap/nextcloud/33908/htdocs/lib/private/Http/Client/Client.php line 218
    GuzzleHttp\Client->request()
13. /var/snap/nextcloud/33908/nextcloud/extra-apps/richdocuments/lib/Service/CapabilitiesService.php line 136
    OC\Http\Client\Client->get()
14. /var/snap/nextcloud/33908/nextcloud/extra-apps/richdocuments/lib/Service/CapabilitiesService.php line 74
    OCA\Richdocuments\Service\CapabilitiesService->refetch()
15. /var/snap/nextcloud/33908/nextcloud/extra-apps/richdocuments/lib/AppInfo/Application.php line 80
    OCA\Richdocuments\Service\CapabilitiesService->getCapabilities()
16. /snap/nextcloud/33908/htdocs/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 67
    OCA\Richdocuments\AppInfo\Application->OCA\Richdocuments\AppInfo\{closure}("*** sensitive parameters replaced ***")
17. /snap/nextcloud/33908/htdocs/lib/private/AppFramework/Bootstrap/BootContext.php line 51
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn()
18. /var/snap/nextcloud/33908/nextcloud/extra-apps/richdocuments/lib/AppInfo/Application.php line 135
    OC\AppFramework\Bootstrap\BootContext->injectFn()
19. /snap/nextcloud/33908/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php line 190
    OCA\Richdocuments\AppInfo\Application->boot()
20. /snap/nextcloud/33908/htdocs/lib/private/legacy/OC_App.php line 208
    OC\AppFramework\Bootstrap\Coordinator->bootApp()
21. /snap/nextcloud/33908/htdocs/lib/private/legacy/OC_App.php line 141
    OC_App::loadApp()
22. /snap/nextcloud/33908/htdocs/ocs/v1.php line 57
    OC_App::loadApps()
23. /snap/nextcloud/33908/htdocs/ocs/v2.php line 23
    require_once("/snap/nextcloud/33908/htdocs/ocs/v1.php")

GET /ocs/v2.php/apps/user_status/api/v1/user_status?format=json
from 192.168.113.4 by Poullain Maxime at 2023-03-14T10:16:48+00:00
#### OS/snapd/snap version

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.4snap1  33908  latest/stable  nextcloud✓  -

snap    2.58.2
snapd   2.58.2
series  16
debian  11
kernel  5.10.0-21-amd64
#### Logs

[debugging.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/10967228/debugging.txt)

**Comment by scubamuc** [comment] 2023-03-14 10:37
duplicate of #2309

disable (Collabora) CODE (shows guzzlhttp error when (CODE) RichDocumentServer is enabled)
find app `sudo nextcloud.occ app:list`
disable app `sudo nextcloud.occ app:disable richdocumentscode`

Nextcloud-office and Collabora not supported on Nextcloud-snap #2288

**Closed** 2023-03-14 15:31 UTC

**Comment by scubamuc** [comment] 2023-10-08 08:32
See working configuration here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap
