### ISSUE TITLE
Missing php-imagick

### ISSUE THREAD

**Issue by CarrionAndOn** [nextcloud-snap/nextcloud-snap#2272] opened 2023-01-13 09:11 UTC
Since it's snap, I can't manually install php-imagick, and it's the only thing appearing in the system scan thing and it's really annoying me. Plus, it prevents people from using the theming feature properly.
![image](https://user-images.githubusercontent.com/30084485/212282056-1cee2cf2-77aa-4e86-95b7-0333616687b5.png)

**Comment by vawaver** [comment] 2023-01-13 09:31
I have the same issue.

**Comment by scubamuc** [comment] 2023-01-13 11:14
please see here: https://github.com/nextcloud-snap/nextcloud-snap/issues/1540

**Comment by kyrofa** [comment] 2023-01-13 16:15
Yes, dupe of #1540. The theming app relies on a library with a terrible security history. We don't want to subject our users to that. As soon as they have a reasonable dependency we can probably support it.

**Closed by kyrofa** 2023-01-13 16:15 UTC
