### ISSUE TITLE
My instance stopped working, constantly goes to mainetance mode

### ISSUE THREAD

**Issue by BugsWorld** [nextcloud-snap/nextcloud-snap#2387] opened 2023-04-19 18:03 UTC
### 
### I was able to look at the logs and these are some of the errors that keep popping up:

Error: chmod(): Permission denied at /var/snap/nextcloud/34372/nextcloud/extra-apps/recognize/lib/Migration/InstallDeps.php#156

GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to localhost port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/extra-apps/richdocumentscode/proxy.php?req=/hosting/capabilities

Failed to install Tensorflow.js: CPU-linux-4.2.0.tar.gz * Downloading libtensorflow https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz events.js:377       throw er; // Unhandled 'error' event       ^  Error: unable to get local issuer certificate     at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)     at TLSSocket.emit (events.js:400:28)     at TLSSocket._finishInit (_tls_wrap.js:937:8)     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) Emitted 'error' event on ClientRequest instance at:     at TLSSocket.socketErrorListener (_http_client.js:475:9)     at TLSSocket.emit (events.js:400:28)     at emitErrorNT (internal/streams/destroy.js:106:8)     at emitErrorCloseNT (internal/streams/destroy.js:74:3)     at processTicksAndRejections (internal/process/task_queues.js:82:21) {   code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }

**Comment by scubamuc** [comment] 2023-04-19 20:22
duplicate of #2288. remove 'richdocumentscode'.
Nextcloud-office ist incompatipble.

**Comment by BugsWorld** [comment] 2023-04-19 21:05
> 1. duplicate of [Nextcloud-snap "feature request" nextcloud-office #2288](https://github.com/nextcloud-snap/nextcloud-snap/issues/2288). remove 'richdocumentscode'.
>        Nextcloud-office ist incompatipble.

Is this a new thing that was added? Because I have been using snap nextcloud for a while and haven't changed much so I'm wondering why I'm experiencing this only now?

**Comment by kyrofa** [comment] 2023-04-19 21:17
This is almost certainly related to third-party apps, as @scubamuc suggests. I'd start by disabling recognize, followed by office, and continue until the problem is resolved, at which point you can log a bug against the offending app.

**Closed by kyrofa** 2023-04-19 21:17 UTC

**Comment by YoannPa** [comment] 2023-07-13 13:58
To add to previous testimonies, I also experienced the in and out maintenance mode bug in 26.0.3snap1
After disabling recognize (and actually removing it definitely right after deactivation) from the interface, I did:
```
sudo nextcloud.occ maintenance:mode --on
sudo nextcloud.occ maintenance:repair
sudo nextcloud.occ maintenance:mode --off
sudo snap restart nextcloud
```
Not sure all the commands are really necessary (I guess the maintenance:repair is the most important).
So far, the problem is solved, and I did not had to revert to the previous version.

So, maybe reverting to the previous version is not always necessary.
Maybe what is really necessary is to deactivate the recognize app, and to `nextcloud.occ maintenance:repair` ?

Thank you very much anyway for the issue, it was extremely helpful to find out what the problem was.
