### ISSUE TITLE
Pop!_OS still incompatible with Nextcloud snap

### ISSUE THREAD

**Issue by Poecilia** [nextcloud-snap/nextcloud-snap#2143] opened 2022-07-27 12:51 UTC
#### Describe the bug
As flagged in 2020, when installing snap Nextcloud on Pop!_OS, there is a bug when you try to run the lets-encrypt certificate. The snap page should not encourage new users to try installing Nextcloud snap on Pop!_OS

#### To Reproduce
1. sudo nextcloud.enable-https lets-encrypt
2. error: An unexpected error occurred: IOError: [Errno 13] Permission denied: '/etc/os-release' Please see the logfile '/tmp/tmpVIQ5Vl' for more details.

#### Expected behavior
For lets-encrypt to work.

#### OS/snapd/snap version
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.1snap1  31033  latest/stable  nextcloud✓  -

snap    2.55.5+22.04
snapd   2.56.2
series  16
pop     22.04
kernel  5.18.10-76051810-generic

The bug is known but 'stale' (?). I would like it to be fixed, but am suggesting that this public page be removed, as Pop!_OS users cannot complete the installation fully:

https://snapcraft.io/install/nextcloud/pop

**Comment by kyrofa** [comment] 2022-07-27 15:25
Dupe of #1348, due to [LP: #1881189](https://bugs.launchpad.net/snapd/+bug/1881189) in snapd. There's nothing we can do here in the snap to resolve this issue, nor do we have the ability to change the recommendations on the snap page. We just control the screenshots and description.

**Closed by kyrofa** 2022-07-27 15:25 UTC

**Comment by Poecilia** [comment] 2022-07-27 17:17
Ok, thanks. Who should I contact to take down that page? It's a shame for people new to this to go through all those steps and then learn they can't complete the final step on Pop OS. The contact link led me to this page.

**Comment by kyrofa** [comment] 2022-07-27 17:19
You'd need to contact Canonical. That page is dynamically generated for every snap by the snap store (for example, [here is slack's](https://snapcraft.io/install/slack/pop)), so I suspect they will not be willing to change their codebase for us.

**Comment by Poecilia** [comment] 2022-07-27 17:21
Ok, I keep hearing on privacy podcasts that installing Nextcloud is relatively easy.  But it's not that easy for beginners. What is the best way to run your own Nextcloud on a hardware device in your home?

**Comment by Poecilia** [comment] 2022-07-27 20:05
Anyway, that aside, I have become kind of a fan of the snap install version, so I think I'll try it all again on Ubuntu.

**Comment by Poecilia** [comment] 2022-07-28 11:34
I have contacted Canonical about removing the page that recommends installing Nextcloud snap on Pop!_OS.
