### ISSUE TITLE
Timeline for update to PHP 8.1 or 8.2

### ISSUE THREAD

**Issue by LoganHub1** [nextcloud-snap/nextcloud-snap#2317] opened 2023-02-17 16:19 UTC
Is there any timeline for PHP 8.1 to be packaged into the snap?  My nextcloud passwords app requires at least PHP 8.1 and is now broken due to being stuck on 8.027.  After updating it recently, I can't access my passwords database.

**Comment by kyrofa** [comment] 2023-02-17 16:31
Nothing is holding us back at this point other than pulling the trigger. There was an attempt to do it in #2260, but it was never entirely completed. I'll get to it when I have some time, but if someone wants to take a crack at it I'd be happy to review. The update from v7 to v8 happened in #1844, for inspiration.

**Comment by kyrofa** [comment] 2023-02-17 16:34
#1483 might be an easier one to reference, since it wasn't a major update. The `extension_dir` thing is the most important.

**Comment by LoganHub1** [comment] 2023-02-17 17:30
Thanks so much for the quick and detailed response.  Glad to hear that it's likely in the works soon.  Appreciate all that you do!

**Comment by kyrofa** [comment] 2023-02-18 14:58
The rooster woke me up at 0430 this morning, so I took the opportunity to throw #2318 together. This issue is technically a dupe of #2259, so I'm going to close, but keep an eye on that PR.

**Closed by kyrofa** 2023-02-18 14:58 UTC
