### ISSUE TITLE
renew-certs broken with "Missing command line flag or config entry for this setting:"

### ISSUE THREAD

**Issue by thedude911** [nextcloud-snap/nextcloud-snap#2930] opened 2024-10-20 11:00 UTC
#### Describe the bug
Renewal of certs working with 29.0.7snap1 but broken with 29.0.8snap1 on Ubuntu 24.04.1

#### To Reproduce
Upgrade to 29.0.8snap1
-> reverting back to 29.0.7snap1 solved the issue

#### Logs
```
2024-10-20 10:55:21,209:WARNING:certbot.renewal:Attempting to renew cert (xxx.com) from /var/snap/nextcloud/current/certs/certbot/config/renewal/xxx.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for xxx.com:. Skipping.
2024-10-20 10:55:21,211:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/renewal.py", line 450, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/main.py", line 1192, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/main.py", line 115, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/renewal.py", line 308, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/client.py", line 349, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/client.py", line 385, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 99, in _set_webroots
    known_webroots)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 144, in _prompt_for_new_webroot
    force_interactive=True)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/display/ops.py", line 371, in validated_directory
    validator, *args, **kwargs)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/display/ops.py", line 328, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/display/util.py", line 583, in directory_select
    return self.input(message, default, cli_flag)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/display/util.py", line 524, in input
    self._interaction_fail(message, cli_flag)
  File "/snap/nextcloud/44391/lib/python2.7/site-packages/certbot/display/util.py", line 469, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Input the webroot for xxx.com:

2024-10-20 10:55:21,211:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2024-10-20 10:55:21,212:ERROR:certbot.renewal:  /var/snap/nextcloud/current/certs/certbot/config/live/xxx.com/fullchain.pem (failure)
2024-10-20 10:55:21,214:INFO:certbot.hooks:Running post-hook command: restart-apache
2024-10-20 10:55:22,553:INFO:certbot.hooks:Output from post-hook command restart-apache:
Restarting apache... done
```

**Comment by scubamuc** [comment] 2024-10-20 12:25
hey @thedude911 welcome and thanks for your request.
> -> reverting back to 29.0.7snap1 solved the issue

well done with that... at least you're up and running again ✅

> `Attempting to renew cert (xxx.com) from /var/snap/nextcloud/current/certs/certbot/config/renewal/xxx.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for xxx.com:. Skipping.`

you could try to [encrypt from scratch](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-HTTP-encryption-(HTTPS)#change-lets-encrypt-domain----lets-encrypt-from-scratch)

@pachulo do you have an idea?

**Comment by scubamuc** [comment] 2024-10-20 12:29
@thedude911 

could you post the output of `sudo cat /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log`

**Comment by pachulo** [comment] 2024-10-20 22:36
Strange: we didn't touch anything related to certbot on the update...
Can you reproduce the issue @scubamuc or @Pilzinsel64 ?

**Comment by scubamuc** [comment] 2024-10-21 06:43
@pachulo can't reproduce => reverse proxy with termination 🤔

**Comment by scubamuc** [comment] 2024-10-21 06:49
@thedude911 could you please post the output of the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script)

**Comment by thedude911** [comment] 2024-10-21 07:34
I can confirm that it is not related to the upgrade, I reloaded my maschine and coming up with 29.0.7snap1 having the same issue as after the upgrade. See the output of the debug script attached.
[res.txt](https://github.com/user-attachments/files/17456840/res.txt)

**Comment by scubamuc** [comment] 2024-10-21 07:47
@thedude911 

```
Okt 21 07:20:50 ubuntu nextcloud.renew-certs[61098]: Cert is due for renewal, auto-renewing...
Okt 21 07:20:50 ubuntu nextcloud.renew-certs[61098]: Non-interactive renewal: random delay of 177 seconds
Okt 21 07:23:47 ubuntu nextcloud.renew-certs[61098]: Plugins selected: Authenticator webroot, Installer None
Okt 21 07:23:47 ubuntu nextcloud.renew-certs[61098]: Renewing an existing certificate
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: Performing the following challenges:
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: http-01 challenge for xxx.com
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: Cleaning up challenges
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: Attempting to renew cert (xxx.com) from /var/snap/nextcloud/current/certs/certbot/config/renewal/xxx.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: Input the webroot for xxx.com:. Skipping.
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: All renewal attempts failed. The following certs could not be renewed:
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]:   /var/snap/nextcloud/current/certs/certbot/config/live/xxx.com/fullchain.pem (failure)
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: All renewal attempts failed. The following certs could not be renewed:
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]:   /var/snap/nextcloud/current/certs/certbot/config/live/xxx.com/fullchain.pem (failure)
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Okt 21 07:23:48 ubuntu nextcloud.renew-certs[61098]: Running post-hook command: restart-apache
Okt 21 07:23:50 ubuntu nextcloud.renew-certs[61098]: Output from post-hook command restart-apache:
Okt 21 07:23:50 ubuntu nextcloud.renew-certs[61098]: Restarting apache... done
Okt 21 07:23:50 ubuntu nextcloud.renew-certs[61098]: 1 renew failure(s), 0 parse failure(s)
```
you could try to [encrypt from scratch](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-HTTP-encryption-(HTTPS)#change-lets-encrypt-domain----lets-encrypt-from-scratch)

**Comment by thedude911** [comment] 2024-10-21 09:09
So "encrypt from scratch" actually did solve the issue for now, both after reload and upgrade to 29.0.8snap1 the log now shows "Cert not yet due for renewal", which is the expected outcome, so I have to wait and see how it goes once the certificate is up to renewal again.

**Comment by scubamuc** [comment] 2024-10-21 09:11
@thedude911 
>  did solve the issue for now

great news, do you wanna close this then?

**Closed** 2024-10-21 09:13 UTC
