### ISSUE TITLE
I can't get rid of the update notifications

### ISSUE THREAD

**Issue by hitindags** [nextcloud-snap/nextcloud-snap#2350] opened 2023-03-10 15:27 UTC
Every time the snap updates itself, I get a notification that I cannot dismiss in both, browser and app. Is there a way to disable the update notifications - or at least, reduce them to the most recent?

**Comment by kyrofa** [comment] 2023-03-10 17:24
I can't reproduce this-- I can dismiss the update notifications just fine. I'm afraid there isn't a way to disable them today.

**Comment by kyrofa** [comment] 2023-03-10 17:46
I can't speak to the app, but I just now updated my server and successfully dismissed the notification :man_shrugging: .

**Comment by hitindags** [comment] 2023-03-10 18:00
Doesn’t the snap update automatically? It‘s the snap update notifications I cannot dismiss. Not sure we are talking about the same thing..

**Comment by hitindags** [comment] 2023-03-10 18:04
![CD0ECCF4-B0AE-4CFB-87E2-67DCC4FBB093](https://user-images.githubusercontent.com/77179463/224390637-ee35ea94-f3db-42a7-bd23-212731771a86.jpeg)

**Comment by kyrofa** [comment] 2023-03-10 18:07
Yes, but I did it manually because I always test out a new release on my prod server before rolling it out to everyone else-- we're talking about the same thing. If I click that X, the message goes away.

**Comment by NaXal** [comment] 2023-03-11 07:06
Hello,

I think these two issues are related -> https://github.com/nextcloud-snap/nextcloud-snap/issues/2300

I was having issues with notification too, neither I could expand the list, nor I could dismiss individual notifications. Issue started with Snap Nextcloud v25. It was fine with v24.

However, last night snap updated to 25.0.4snap1 and the notification issue seems to be fixed. I can now expand indvidual notifications and close or dismiss either the entire list or individual notifications.

![01](https://user-images.githubusercontent.com/91847371/224470420-b18dcdd5-c26e-476b-a77a-2304bd03c945.jpg)

Thanks.

**Comment by hitindags** [comment] 2023-03-11 09:11
Yes! It’s working. Thank you for noticing!

**Comment by kyrofa** [comment] 2023-03-11 15:18
Odd, must have been an upstream issue indeed, then. Thanks for linking them, @NaXal. I'll go ahead and close this, then.

**Closed** 2023-03-11 15:20 UTC
