### ISSUE TITLE
nextCloud want to "opcache.interned_strings_buffer=8"

### ISSUE THREAD

**Issue by neeks76** [nextcloud-snap/nextcloud-snap#2261] opened 2022-12-22 12:38 UTC
My nextCloud request to "opcache.interned_strings_buffer=8"

To change php.ini, I tried it at /snap/nextcloud/32871/config/php/php.ini

But, I couldn't edit it becatuse of Read-only file system.
chmod, remount, all of that can't avoid write-protected.

Could you show me how to change?

**Comment by scubamuc** [comment] 2022-12-26 11:02
@neeks76 
see here #2024 
maybe you can help devs? 
otherwise stand by...

**Comment by kyrofa** [comment] 2022-12-30 16:56
Indeed, dupe of #2024.

**Closed by kyrofa** 2022-12-30 16:56 UTC
