### ISSUE TITLE
PHP 8 update: performance improvement?

### ISSUE THREAD

**Issue by sintomaticonegativo** [nextcloud-snap/nextcloud-snap#1835] opened 2021-09-09 07:57 UTC
Probably I'm wrong, but after REDIS update i think that the next step should be PHP 8.

Could be a good improvement for the nextcloud experience?

**Comment by kyrofa** [comment] 2021-09-10 15:51
No you're right, this has been on our radar for a while. This is a dupe of #1654, let's track it over there.

**Closed by kyrofa** 2021-09-10 15:51 UTC
