### ISSUE TITLE
PHP SOAP in SNAP-container 'nextcloud_39212.snap'

### ISSUE THREAD

**Issue by ParadiseWarfare** [nextcloud-snap/nextcloud-snap#2664] opened 2024-01-31 05:23 UTC
Hello,
Please add the following line to the "php configflags" section in the 'snapcraft.yaml' file: "- --with-soap".

For the proper functioning of the "Exchange EWS Connector (Exchange Web Services) for Nextcloud" application (https://github.com/ksainc/integration_ews?tab=readme-ov-file#basic-requirements) PHP SOAP is required.

I am unable to enable this application and encounter the following error: 'App "Exchange EWS Connector (Exchange Web Services)" cannot be installed because the following dependencies are not fulfilled: The library soap is not available.'

**Comment by kyrofa** [comment] 2024-01-31 05:26
Dupe of #1317:

> Sorry, we have a standing policy of not packing dependencies in to enable apps other than the core (bundled or recommended) apps, otherwise the snap would grow to infinite size.

**Closed by kyrofa** 2024-01-31 05:26 UTC
