### ISSUE TITLE
Internal Server Error: "ParseError: Unterminated comment ... in ... Redis.php"

### ISSUE THREAD

**Issue by mieseprem** [nextcloud-snap/nextcloud-snap#2219] opened 2022-10-30 13:43 UTC
Hello,

I wonder why my SNAP Nextcloud instance starts throwing theses exceptions since yesterday.

I guess there is a relation between this issue and kernel 6 (which was installed on host system yesterday).

> $ sudo snap list
> Name       Version      Rev    Tracking       Publisher   Notes
> core18     20220831     2566   latest/stable  canonical✓  base
> nextcloud  24.0.6snap1  31751  latest/stable  nextcloud✓  -
> snapd      2.57.4       17336  latest/stable  canonical✓  snapd

With kernel 5.19 it is working:

> $ uname -srvmpio
> Linux 5.19.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 16 22:50:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> $ sudo nextcloud.occ --version
> Nextcloud 24.0.6

With kernel 6.0 not:

> $ uname -srvmpio
> Linux 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> $ sudo nextcloud.occ --version
> mkdir: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verdef record
> mkdir: error while loading shared libraries: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verneed record

:exclamation: In the attached log you will find a different error. I don't know why, but the error message differs between reboots.

This is the host machine:

> $ cat /etc/os-release 
> NAME="Fedora Linux"
> VERSION="36 (Server Edition)"
> ID=fedora
> VERSION_ID=36
> VERSION_CODENAME=""
> PLATFORM_ID="platform:f36"
> PRETTY_NAME="Fedora Linux 36 (Server Edition)"
> ANSI_COLOR="0;38;2;60;110;180"
> LOGO=fedora-logo-icon
> CPE_NAME="cpe:/o:fedoraproject:fedora:36"
> HOME_URL="https://fedoraproject.org/"
> DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
> SUPPORT_URL="https://ask.fedoraproject.org/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_BUGZILLA_PRODUCT="Fedora"
> REDHAT_BUGZILLA_PRODUCT_VERSION=36
> REDHAT_SUPPORT_PRODUCT="Fedora"
> REDHAT_SUPPORT_PRODUCT_VERSION=36
> PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
> VARIANT="Server Edition"
> VARIANT_ID=server

Logs: 
[logs-censored.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9895955/logs-censored.txt)

I know, this could be an issue of occ (nextcloud itself) or Snap or Fedora or Kernel.
But if anyone of you is able to reproduce this on a different system we can exclude all parts as origin that are different.

**Comment by kyrofa** [comment] 2022-10-30 14:31
Dupe of #2209, that kernel appears to have squashfs issues.

**Closed by kyrofa** 2022-10-30 14:31 UTC

**Comment by kyrofa** [comment] 2022-11-08 17:07
It sounds like the fix has landed in v6.0.7, FYI.
