### ISSUE TITLE
Notification List (Bell icon on toolbar) - disappears when clicking  X of individual notification

### ISSUE THREAD

**Issue by aquananu** [nextcloud-snap/nextcloud-snap#2300] opened 2023-02-06 14:35 UTC
nextcloud 25.0.2 / 25.0.3 snap - both versions
notification app 2.13.1

the list of notification closes when any individual notification is cleared by clicking the X in the list see gif below
![nextcloud notifications](https://user-images.githubusercontent.com/93096176/216999206-5f64fee4-d11f-49a5-8639-de9026cb99a6.gif)

**Comment by szaimen** [comment] 2023-02-06 15:38
I think this will be fixed with 25.0.4

**Comment by kyrofa** [comment] 2023-02-06 16:12
Yes this appears to be an upstream Nextcloud issue-- not something we can fix in the snap. @szaimen do you know if an issue has been logged for this?

**Comment by szaimen** [comment] 2023-02-06 16:14
In the notification app repo somewhere iirc

**Comment by NaXal** [comment] 2023-02-07 07:54
I am facing the same problem. I just came to report and saw its already posted here.

I can confirm this issue started after v25 snap original release. It wasn't the case with v24.

Thanks.

**Comment by NaXal** [comment] 2023-03-11 07:07
Hello,

I would like to add update to this issue of mine,

Last night snap nextcloud updated to 25.0.4snap1 and the notification issue seems to be fixed. I can now expand individual notifications and close or dismiss either the entire list or individual notifications.

![01](https://user-images.githubusercontent.com/91847371/224470490-9c7a856a-6d85-4cdf-9438-0e956e716e7c.jpg)

Thanks.

**Comment by kyrofa** [comment] 2023-03-11 07:12
Thanks for the update @NaXal! I'll go ahead and close this, then.

**Closed by kyrofa** 2023-03-11 07:12 UTC
