### ISSUE TITLE
Snap's MariaDB/MySQL prevents use of other DB on host, while also not usable by other applications

### ISSUE THREAD

**Issue by coyoteconscious** [nextcloud-snap/nextcloud-snap#2679] opened 2024-02-12 06:53 UTC
#### Describe the bug
I installed Nextcloud Snap on a brand-new server with nothing else on it. Everything went fine, and it ran well with minimal configuration. And _then_ I tried to install Wordpress on the same host. When I got to the MariaDB/MySQL installation for the host server, I discovered that the Snap version hogs the default ports/socket.

I want to be able to run other MariaDB-enabled applications on the same host machine without making every other app besides the Snap Nextcloud use alternate everything.

#### To Reproduce
1. Install Nextcloud Snap
2. Try to install MariaDB on host machine
3. Watch it fail and be frustrated

#### Expected behavior
I expect the Nextcloud Snap, with it's self-contained install, to be self-contained and not interfere with the installation of other applications on the same device.

#### OS/snapd/snap version
nextcloud  27.1.6snap1  40228  latest/stable  nextcloud✓  -
snap    2.61.1
snapd   2.61.1
series  16
ubuntu  23.10
kernel  6.5.0-17-generic

#### Logs
See attachment
[snap-nextcloud-errorlog.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/14235701/snap-nextcloud-errorlog.txt)

**Comment by scubamuc** [comment] 2024-02-12 10:51
Welcome and thank you for your request.

did you try changing the ports at all see [HTTP/HTTPS port configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Port-configuration)

maybe you'd like to use a reverse proxy? See [Reverse proxy configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy)

you say Nextcloud snap worked fine until you installed something else... so Nextcloud snap is certainly not the issue here?

**Comment by coyoteconscious** [comment] 2024-02-12 13:54
Scubamuc: No, you have misapprehended the nature of my problem.

Nextcloud snap is working. It prevents anything else that might need a database from working because it installs MariaDB using the sockets and ports used by default by systems in general, but does not allow its database to be used by other software.

This means that if you install Nextcloud Snap, it prevents _other_ applications from working.

And yes, that is a Nextcloud Snap issue.

If I installed Microsoft Word on my computer, and it prevented all other office applications from working, nobody would think that was okay, would they?

**Comment by coyoteconscious** [comment] 2024-02-12 13:57
Additionally, you offered suggestions about changing the http ports and setting up reverse proxy. Those are web service ports, not database ports. Altering the web service points has nothing at all to do with the database connectivity within the server. Those ports are used to send web content to a person's browser. The database socket connection is used here for the server to connect to the database internally.

**Comment by coyoteconscious** [comment] 2024-02-12 13:59
You closed this topic without answering, or even addressing the real issue. Worse, you did so after providing unrelated information about a different issue that I do not have and did not ask about.

**Comment by pachulo** [comment] 2024-02-12 16:10
Hi @coyoteconscious . Please, temper your mood, we are all volunteers here. Maybe @scubamuc was wrong, but he was trying to assist and help you. If this was wrongly closed it can be opened again, no need to open another issue with a [harsh comment](https://github.com/nextcloud-snap/nextcloud-snap/issues/2680#issuecomment-1938755532).

**Comment by pachulo** [comment] 2024-02-12 16:16
I think this the expected behaviour, isn't @kyrofa ?

The nextcloud snap is meant to be as straightforward as possible, that's why it doesn't offer options to modify such internal technical details.

As a workaround I guess you could run the nextcloud snap inside a LXD/Incus container if you cannot/don't want to modify every other app.

**Comment by kyrofa** [comment] 2024-02-12 16:37
> When I got to the MariaDB/MySQL installation for the host server, I discovered that the Snap version hogs the default ports/socket.

I'm not entirely sure what you're talking about, but if you're saying the mysql in the snap prevents you from running mysql outside of the snap, then something is wrong indeed.

> I expect the Nextcloud Snap, with it's self-contained install, to be self-contained and not interfere with the installation of other applications on the same device.

Spot on, that's definitely our goal. Focusing in on how we use mysql, we shouldn't be using ANY ports (we [disable networking entirely](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/my.cnf#L5)). The only entrypoint into the snap-shipped mysql [should be its socket](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/support-files/mysql.server#L209), which is in the [snap-specific subdirectory within /tmp](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/utilities/mysql-utilities#L8).

Can you expand a little on what exactly you're seeing, here?

**Comment by coyoteconscious** [comment] 2024-02-12 17:18
> Spot on, that's definitely our goal. Focusing in on how we use mysql, we shouldn't be using ANY ports (we [disable networking entirely](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/my.cnf#L5)). The only entrypoint into the snap-shipped mysql [should be](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/support-files/mysql.server#L209) its [unix socket](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/nextcloud/config/autoconfig.php#L14), which is in the [snap-specific subdirectory within /tmp](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/utilities/mysql-utilities#L8). It is definitely intended to be private and not interfere with anything.

Okay, we're getting somewhere! Thank you!

What I am saying is that it is indeed not allowing other MySQL or MariaDB services to run.

If that is _not_ supposed to happen with the snap install, and the primary mariadb on the host is supposed to be unaffected, and it and nextcloud snap are meant to be able to coexist, that's definitely not what's happening. I can either run the nextcloud snap, and it can use it's db, or I can run the host mariadb or mysqldb, and be unable to run the nextcloud snap. It looks like they are both attempting to use the same service name.

If I start the nextcloud snap, and do service --status-all, it shows MariaDB as a service. If I stop it, it goes away. If I start the host mariadb, of course, same thing happens, as long as the nextcloud snap is stopped. I get a service of that name. It's a default install of mariadb on ubuntu. I made no changes or customizations to it.

If I attempt to start the nextcloud snap while the host db is running, or vice versa, of course, I get an error saying there is already a service there.

I apologize if I came across as short. I felt like the concern was being dismissed out of hand by someone that didn't even really read the issue fully - leaving the real issue unaddressed for me and anyone else it might happen to.

I tried to provide a detailed explanation of a confusing problem, and spent a lot of time experimenting seeing if I could troubleshoot that problem before I came here.

Then I got a response that felt like the person A: paid no attention to anything I'd said, and B: seemed more interested in finding a reason not to help. It also made me C: might not know the difference between a database connection and an http/https connection.

I hope you can understand that after hours of trying to figure out what was going on, to get shut down that way is frustrating and discouraging. Me spending hours working out what was going on, so that if it happened to someone else, they wouldn't have to is also "volunteer" work. I was attempting to communicate a problem that seemed serious.

**Comment by kyrofa** [comment] 2024-02-12 17:25
> It looks like they are both attempting to use the same service name.

We're talking systemd units, here?

> If I start the nextcloud snap, and do service --status-all, it shows MariaDB as a service. If I stop it, it goes away.

To be clear, we don't use MariaDB, so that makes no sense. Here are all the snap's services:

```
$ snap services nextcloud
Service                    Startup  Current   Notes
nextcloud.apache           enabled  active    -
nextcloud.logrotate        enabled  inactive  timer-activated
nextcloud.mysql            enabled  active    -
nextcloud.nextcloud-cron   enabled  active    -
nextcloud.nextcloud-fixer  enabled  inactive  -
nextcloud.php-fpm          enabled  active    -
nextcloud.redis-server     enabled  active    -
nextcloud.renew-certs      enabled  active    -
```

Each of these turn into a systemd unit that follow a particular snap-specific naming pattern, for example:

```
$ systemctl status snap.nextcloud.mysql.service 
● snap.nextcloud.mysql.service - Service for snap application nextcloud.mysql
     Loaded: loaded (/etc/systemd/system/snap.nextcloud.mysql.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-02-11 01:05:59 AKST; 1 day 7h ago
    Process: 98558 ExecReload=/usr/bin/snap run --command=reload nextcloud.mysql (code=exited, status=0/SUCCESS)
   Main PID: 589 (start_mysql)
      Tasks: 49 (limit: 18875)
     Memory: 379.3M
     CGroup: /system.slice/snap.nextcloud.mysql.service
             ├─   589 /bin/sh -e /snap/nextcloud/40228/bin/start_mysql
             ├─  1029 /bin/sh /snap/nextcloud/40228/bin/mysqld_safe --defaults-file=/snap/nextcloud/40228/my.cnf --datadir=/var/snap/nextcloud>
             ├─  1321 /snap/nextcloud/40228/bin/mysqld --defaults-file=/snap/nextcloud/40228/my.cnf --basedir=/snap/nextcloud/40228 --datadir=>
             └─133491 sleep 1

Feb 11 01:05:59 nextcloud systemd[1]: Started Service for snap application nextcloud.mysql.
Feb 11 01:06:20 nextcloud nextcloud.mysql[949]: Starting MySQL
Feb 11 01:06:38 nextcloud nextcloud.mysql[949]: ................ *
Feb 12 00:00:12 nextcloud systemd[1]: Reloading Service for snap application nextcloud.mysql.
Feb 12 00:00:13 nextcloud systemd[1]: Reloaded Service for snap application nextcloud.mysql.
```

> If I start the host mariadb, of course, same thing happens, as long as the nextcloud snap is stopped. I get a service of that name. It's a default install of mariadb on ubuntu. I made no changes or customizations to it.
> 
> If I attempt to start the nextcloud snap while the host db is running, or vice versa, of course, I get an error saying there is already a service there.

Can you show me the error you're seeing, please?

**Comment by coyoteconscious** [comment] 2024-02-12 17:56
I'd already resigned myself to doing another manual install and have already uninstalled. If you're serious about actually tracking this down with me, I will do another reinstall of the snap version later after I've gotten some sleep, and see. I've currently got that default install of MariaDB installed, but I will probably uninstall and purge that to start fresh.

**Comment by kyrofa** [comment] 2024-02-12 18:03
Up to you. We've put a lot of work into keeping this thing isolated, and what I've seen so far does not convince me that it's not working properly, but it's clear that _something_ isn't working right for you. If you can actually describe what you're seeing with some data that makes it:

1. Clear that it's a bug now that you know it should indeed be isolated
2. Reproducible by us

Then it's something we can fix for you. If you'd rather install manually, that's of course fine as well.

**Comment by scubamuc** [comment] 2024-02-12 20:08
> If I start the nextcloud snap, and do service --status-all, it shows MariaDB as a service. If I stop it, it goes away. If I start the host mariadb, of course, same thing happens, as long as the nextcloud snap is stopped. I get a service of that name. It's a default install of mariadb on ubuntu. I made no changes or customizations to it.

so I went ahead and tested this:

- Nextcloud snap installed 
- mysql installed (`sudo apt install mysql-server-8.0`) 

issue command: `systemctl status --all | grep mysql.service`

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/bb412c51-5e33-4533-a31d-5ab3dabd97a8)

double check using tmux:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/51d99157-9ba6-4c09-a97e-e2de43840b4c)

mysql running, cloud running, no issues:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/d9e94a4e-cfea-46c3-90e0-f88021d1a3e1)

> If I installed ~~Microsoft Word~~ on my computer, and it prevented all other office applications from working, nobody would think that was okay, would they?

not a chance....

**Comment by scubamuc** [comment] 2024-02-12 20:23
oh, same same with mariadb installed:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/af4a4071-c322-4586-a365-ac2ec3f17a79)

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/ad8a2a94-5973-4df0-a2c7-f662ffcc9335)

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/f01b1dc8-202c-4da3-8ace-1bd6326c6dc9)

**Comment by coyoteconscious** [comment] 2024-02-13 01:30
I'm glad you could get it to work - I hope I'm the only person who had the problem then. Like I said I will do another install of it tonight and see if I can reproduce the behavior.

It looks like you did basically the same sort of install I did, with different results from me. I also installed the snap, then installed MariaDB, in that order.

Was the machine you did your tests on a clean install, like mine, or was it an existing copy of Ubuntu?

**Comment by coyoteconscious** [comment] 2024-02-13 06:46
I have a new install of Nextcloud Snap installed on a clean new server with nothing else installed but what came as default.

Attached, please find a text dump of my terminal, wherein I start by demonstrating that the Nextcloud snap is running, then that there is no host database service running (because it has not been installed yet).

Then I install MariaDB, and you will note that near the end, there are errors:
`Failed to stop mariadb.service: Unit mariadb.service not loaded.`

If I stop the Snap Nextcloud, it will allow me to start the MariaDB service, but not the Nextcloud instance. If I have the Nextcloud instance running, it will not allow me to start MariaDB.

Again, this is a fresh install of Ubuntu.
[failed-mariadb-install.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/14257151/failed-mariadb-install.txt)

Is there anything else you would like to look at, or would like me to try?

**Comment by coyoteconscious** [comment] 2024-02-13 10:03
I see that even though I'd agreed to do more testing to figure out what was going on in my install, you all decided to close the ticket again. I didn't realize until after I put more hours in on this that you'd decided to abandon it again.

I guess as long as it works on your system, you don't care if doing what should be a standard install results in problems for some of your users. I didn't realize we were debugging and testing your functioning system. I thought we were trying to figure out what went wrong on mine.

My mistake.

**Comment by scubamuc** [comment] 2024-02-13 10:16
@coyoteconscious you closed the issue yourself:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/843357ff-8c9d-4194-acfd-d57d94465c8e)

**Comment by coyoteconscious** [comment] 2024-02-13 10:21
I deeply apologize. I absolutely do not recall doing that. My mistake. I must have allowed my frustration at the problem to color my judgment, and made me jump to a conlusion.

**Comment by coyoteconscious** [comment] 2024-02-13 10:21
In any case, if you would like to try and figure this out with me, I'd appreciate it. If you're not willing to look into this any more, I'll go occupy myself doing something less frustrating.

**Comment by kyrofa** [comment] 2024-02-13 17:38
I'm going to go ahead and close this issue because because it's not something we can fix, but please feel free to continue discussion here.

**Closed by kyrofa** 2024-02-13 17:38 UTC

**Comment by scubamuc** [comment] 2024-02-13 18:45
Oh wow,

> On Ubuntu 23.10, mariadb-server has a preinst ....

**Ubuntu 23.10** - I missed that completely in my tests, maybe I should pay better attention?

**Comment by coyoteconscious** [comment] 2024-02-14 04:59
> > On Ubuntu 23.10, mariadb-server has a preinst ....

See? I'm not crazy!
I mean, I am, but not about this!

I really appreciate your patience with me on this, and I am sorry for my part in where the conversation was unpleasant.

Would you like to make a bug report to Ubuntu, since you are likely to understand better how to explain the issue, or would you prefer I do it? I may not be the most charming bug reporter on the planet.

**Comment by coyoteconscious** [comment] 2024-02-14 05:53
I'm going to give this another try, and see if I can get the database installed first, keep it stopped, then install Nextcloud Snap again. I'm disabled and retired, so I have time to spend. Can you tell by how cranky I act? : )

Again, my intent for this is to come up with an easy path-to-success for the intended audience (non-power users), who might want multiple personal cloud apps. Nextcloud is quite awesome, but it does not meet every need by itself. Think retirees who learn how to use the computer by going to a free class at the local library.

A lot of folks have the idea that the user needs to learn how to talk to the computer properly, and think the difficulty is they won't or can't be trained, so it is their fault when something doesn't work.

But what we're really writing software for is not so people can talk to computers - we are doing it so computers can communicate with and assist _human beings_. The goal is not to punish the end user for not knowing how computers work, it is to get the computer to function in ways that are human-readable and human-useful, without requiring them to stop thinking like humans and act like something else.

It doesn't matter how good the code is (or whose responsibility it is to fix the issue), if the user can't understand it or recover from error. And there's always going to be glitches and problems that need to be recovered from. Nobody is getting on the Gattaca.

The target demographic for Nextcloud Snap is primarily people who are not as technically literate, who need an easy install. If trying to also install Wordpress (which is normally really easy) causes problems (because it requires a database), a lot of that target market will just give up. They might not even know to come here and say anything.

I'm certain that things work fine for almost all users, but if there's an intuitive path-to-failure that people can fall into, it's worth looking for a workaround. Sometimes the error is not in code, it's in the order of operations and the path the user takes to install or work with it. You're not just debugging code, you're also debugging the expected and actual behavior of end-users.

The most important component of any computerized system is the human component. You cannot program human interfaces without accounting for the actions, misconceptions, and intuitive biases of the users - they are a moving part of your application! You can't predict every silly thing a person might do, but if you throw your hands up and ignore the human element, human cognitive and intuitive biases, that way lies pain.

And software doesn't exist in a vacuum. Your software always has to work with other people's software, and they won't be perfect either, and they won't always tailor their work to suit your software's needs. That's just how things are. You still have to either find a workaround or see your stuff break. It doesn't matter whose fault it is, you either find a solution or it stays broken. 

If your stuff blows up because a user might install it before something instead of after, you should at least be able to warn them not to install before instead of after (or if it can't work on a certain system, warn them "by the way, don't use this if...".

They won't understand that the mariadb installer isn't able to blah-dee-blah-computer-stuff. They'll just know they tried to follow the directions and it didn't work.

And if the response to a user complaining that something didn't work is to act like it's their problem, or not believe them, or tell them that it works on your machine, that's not going to fix anything. It doesn't need to work on your machine, it needs to work on theirs. When someone is frustrated and asks for help, if you treat them like the problem and get defensive, how do you think they will respond? Do you think they will go "Oh, they're volunteers, so it's okay if they are bad at talking to people" or "Wow, these guys are !#$@$#%'s"?

What's that old joke?
Salesman: I need to show the software to the client, but it's broken.
Developer: It works fine on my development machine.
Salesman: Then I guess I'm taking your development machine to the demo!

When in doubt, think "What Would Tron Do?"
The answer is "Serve the User."

The goal is to make the machine work for the person. It's the person that is important. So if you aren't helping the person, you're failing the mission. It's not about blame, it's not about seeing which issues can be dismissed, it's not about who made which mistake, it's about getting something working. There can be no pride in development except the pride of seeing it work for your end-users.  If your pride makes you defensive, it'll also encourage you to hide your errors, and that leaves things broken. It'll cause you to treat the human as the enemy instead of treating the problem as the enemy.

Bitchy old person rant over.

**Comment by coyoteconscious** [comment] 2024-02-14 07:11
Anyway, to the actual topic: Here is a path to success (it may not be the only one, but it appears to have worked for me).

Installed the same Ubuntu system fresh install.
Installed MariaDB as normal.
Ran mysql_secure_installation (Most MariaDB tools refer to or are aliased to MySQL, as it is meant as a drop-in replacement)
Stopped MariaDB (just in case)
Installed Nextcloud Snap
Restarted MariaDB

Looks like life is good!

So it looks like all that needs to happen is that you need to make sure Nextcloud Snap is _not_ running when doing your MariaDB/MySQL install. That's good news!

**Comment by scubamuc** [comment] 2024-02-14 07:25
@coyoteconscious, well that is good news!

**Comment by kyrofa** [comment] 2024-02-14 10:18
Careful @coyoteconscious, in a Debian package, the preinst also runs whenever the package upgrades. You have a ticking time bomb, there.

**Comment by coyoteconscious** [comment] 2024-02-16 04:28
> Careful @coyoteconscious, in a Debian package, the preinst also runs whenever the package upgrades. You have a ticking time bomb, there.

What do you recommend, other than not using Nextcloud Snap?

**Comment by coyoteconscious** [comment] 2024-02-16 08:00
It just feels like the mission of "this installation will be easy for non-technical users" is not quite being met. It's feeling more like "as long as this is the only thing on your box or as long as you are not using a debian-based solution like Debian or Ubuntu, it will be fine."

Debian and its forks, like Ubuntu, are extremely popular. So is Mariadb. Nextcloud Snap being unable to safely coexist with those seems like a problem. Is that an unreasonable statement to make?

So, if Nextcloud Snap will not safely work on Debian-based systems using the Debian package manager, can you suggest a version of Linux that is better suited, or can you point to solutions for installing these tools on a debian-based systemthat do not use the broken pathway caused by using, say, apt?

Because that would be helpful, more than "you're sitting on a ticking time bomb."

**Comment by scubamuc** [comment] 2024-02-16 08:21
> So, if Nextcloud Snap will not safely work on Debian-based systems using the Debian package manager

see why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for Nextcloud snap

@coyoteconscious if I may suggest not using an intermediate version (Ubuntu 23.10) but using LTS (Ubuntu 22.04) instead... that is best practise and would solve your Database issue immediately.

if you want to make a difference, which you certainly are already doing by finding these issues, it would be a great help if you logged those issues in Ubuntu, Snap and MariaDB... etc.  we can't do much because we're working on Nextcloud snap.

thanks for your efforts and thanks for supporting open source 👌

**Comment by coyoteconscious** [comment] 2024-02-16 09:36
So far, the closest thing y'all have come to offering _any_ solution has been "you shoulda used a different OS."

While I'm asking MariaDB to pretty please fix the thing that breaks your software, and installing a different operating system, should I also let Saker and the Master Control Program know that you're looking for projects to do tech support on?

I agree that I indeed have a bad attitude now. I often have a bad attitude when people are defensive, project fault onto others, won't take responsibilty, and passive aggressively assign blame where being tutelary would suffice.

I now cannot trust your product to work properly if I recommend it to non-technical end users. Period.

Because it can fail in easily-encountered situations, and when that happens, your attitude is "tough noogies, it must be because you r dumm".

The problem is not me, or Ubuntu, or MariaDB, or even your software. It is your ethic.

I can't imagine that even if I _could_ get this to work, that I'd trust it to continue working, because I can't trust that people with attitudes like yours can do good work. Not good enough to put my reputation on the line by recommending it, certainly.

**Comment by coyoteconscious** [comment] 2024-02-16 09:42
Here's a suggestion:

When your thing won't be compatible with something, instead of saying "You shoulda not used that" you say something like "We are _sorry_ that at present, our software is not compatible with that sort of installation. While we will reach out to the makers of that software to help our product integrate better, in the meantime, here is a solution that would get you up and running. Thank you for bringing this matter to our attention. We try very hard to make our solution easy for end users like yourself, and we understand that problems like this are frustrating."

See? I made a helpful solution, instead of _merely_ pointing out what the problem was. It may not be one you use, but I did attempt to offer an alternative to "let's just suck".

**Comment by coyoteconscious** [comment] 2024-02-16 09:53
Remember: Anyone you ever have to work with in your career can see you and judge you by how you respond here. But I'm retired, so nobody can fire me, and I don't need references.

I'm sure you feel like your responses are just great. You really told that guy!

I'm sure most people will look at this and go "I bet these people really care, and have a strong sense of responsibility, and are confident enough to own up to mistakes or problems. I should hire them for my team!"

I bet you could work at Xfinity! I hear their tech support people get a bonus if a customer actually dies while on the call!

**Comment by coyoteconscious** [comment] 2024-02-16 13:17
Also, if the version of Ubuntu I had going was an issue, you might have mentioned that after my first post, where I mentioned the version of Ubuntu I was using, per the information asked for in the issue report. If you're going to ignore stuff like that, then drag someone through a lengthy and unpleasant exposure to your "help" you might as well not ask for it in the first place.

If you want accolades, try doing a decent job. You're like that coworker that everyone's happy when they don't come in to work, because more work gets done if they aren't present. Do you have any idea how much effort it would have saved if you'd just responded that the whole branch I used wasn't something you support or test on? Enough effort you could have contacted MariaDB.

Okay, now, goodbye. I've vented my spleen enough, and now I prefer to drop all of you down the memory hole. Thanks so much for supporting the open source community.

**Comment by kyrofa** [comment] 2024-02-16 14:17
We found the issue, and it's not with our software. You want a fix, talk to the people shipping the software that is broken. That's all we can really offer. Your frustration is misdirected, I'm afraid, and I won't subject my team to it any longer.
