### ISSUE TITLE
Opening office documents works with the current upstream but not with the stable versions of the nextcloud snap on ubuntu server 22.04

### ISSUE THREAD

**Issue by safranat** [nextcloud-snap/nextcloud-snap#2340] opened 2023-03-04 11:27 UTC
When installing the nextcloud snap on ubuntu server 22.04 it is possible to create new collabora documents from the existing templates but it will not open any new or existing documents.
When installing the same snap on ubuntu desktop 22.04 it works.
With the daily build of upstream Nextcloud's master branch from today (2023-03-04) it works on the ubuntu server version too.

Is there any way to get the collabora office working with a stable version of the nextcloud snap on ubuntu server 22.04 ?

Install ubuntu server 22.04
Login to the server via ssh
  sudo -s
  snap install nextcloud
  nextcloud.enable-https self-signed
  vi /var/snap/nextcloud/current/nextcloud/config/autoconfig.php
Change 'directory' => getenv(...), to 'directory' => '/mnt/nextcloud/data',
  snap connect nextcloud:removable-media
  snap restart nextcloud.php-fpm

Login to the nextcloud instance via browser from a different machine.
    Create an admin account
    Select installation of standard apps
    Go to the files section
    Create a new office document or click on an existing one

See error: there is only a white screen with a text like opening document, a running circle and a cancel button. But the document will not open. Office seems to be running. It is possible to create new documents from the existing templates. You can download the new documents and edit them locally on the client machine. Even the new ones which had been created within the nextcloud from the existing templates.

**Comment by safranat** [comment] 2023-03-04 11:36
Please advice if there is a better place to rise this issue.

Kind regards,
SaFran

**Comment by scubamuc** [comment] 2023-03-04 11:39
duplicate of #2288

**Closed** 2023-03-04 15:26 UTC

**Comment by safranat** [comment] 2023-03-04 16:55
Maybe it's not the right place for my question, but I like to find out what the nextcloud snap needs from ubuntu which the desktop version  22.04 provides and the server 22.04 does not. Because everything works well when the same snap is installed on the 22.04 ubuntu desktop version.

**Comment by Pilzinsel64** [comment] 2023-10-06 08:08
@safranat You are absolutely right! While I was troubleshooting to maybe find the reason why so many users have problem with snap, I just found your comment and tried it out.

I have a fresh installed Ubuntu Server 22.04 on the one side, with thrid-party support. Installed Nextcloud Snap. All fine! But CODE doesn't work. Absolutely not. Really. The AppImage itself would work, but for some reason the richdocuments app either fails to start the appimage or even fails before - without log entry of course.

Then I tried this on a fresh installed Ubuntu Desktop 22.04 and installed Nextcloud Snap the same way. richdocuments & richdocumentscode works out of the box!

I'll make an issue on the richdocuments repo again and try to contact the office team via the public chat. There must be just a lib missing that needs to be installed, that must be just a really minor problem.

cc @scubamuc

**Comment by Pilzinsel64** [comment] 2023-10-06 08:24
Alright, I will NOT make an Issue. Just installing `fontconfig` helped me to get this working out of the box on Ubuntu Server 22.04.
See: https://github.com/CollaboraOnline/richdocumentscode#system-requirements

I assume this is probably the root cause for why this doesn't work for so many users. Of course there are other problems too, but this shows, it basically works. Everything else is related to the app itself.

cc @nextcloud-snap/developers  I'm going to adjust the wiki entry. :)

**Comment by scubamuc** [comment] 2023-10-06 11:07
@Pilzinsel64, so I've just run a test on a headless 22.04 incl. [above packages](https://apps.nextcloud.com/apps/richdocumentscode) with `latest/beta`. 

the good news is that the system isn't dying on me due to the exception, and CODE seems to be running with "green" check! 
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/ff7ff866-7a2b-4883-aeb4-4c2bd0bdde05)

But office still isn't working! 
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/f164ee93-46ae-44a3-8d74-1c7a2d5089b6)

It would be great if we found the missing packages so that these work in headless mode? I'm guessing these would have to be included in the snap? I'm not sure installing them on the host will be enough?

**Comment by scubamuc** [comment] 2023-10-06 11:28
> What appears when calling this address? http://youtdomain.com/extra-apps/richdocumentscode/proxy.php?req=/hosting/capabilities

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/97b74df5-6b12-4fb2-bc2e-e69152718694)

> What is the output of this command? sudo fusermount -V

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/7452e128-302b-4066-b166-f22834c8335d)

**Comment by Pilzinsel64** [comment] 2023-10-06 11:33
@scubamuc Alright. This warning is fine here. Is the green checkmark still there if you click on "Built-In CODE" option or will get it red?
I'm asking because the green checkmark is default here. It will only show you the correct state if you manually trigger it.

Also, another idea. What is the output of the command `( /sbin/ldconfig -p || scanelf -l ) | grep fontconfig` for you?

**Comment by Pilzinsel64** [comment] 2023-10-06 11:38
Also, what is the output of this address?
https://yourcloud.com/index.php/apps/richdocuments/settings/fonts.json

**Comment by scubamuc** [comment] 2023-10-06 11:39
> This warning is fine here. Is the green checkmark still there if you click on "Built-In CODE" option or will get it red?

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/959cddf5-a9ff-4d90-9294-10915656f6d9)

> Also, another idea. What is the output of the command ( /sbin/ldconfig -p || scanelf -l ) | grep fontconfig for you?

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/fafc8bc7-e441-43c3-ae5b-cc4a26c5e194)

... loong list, no errors

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/02582774-820c-4b11-92b5-053ea24e5e8e)

**Comment by Pilzinsel64** [comment] 2023-10-06 11:40
@scubamuc Try again with the "(" and ")", see:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/0cac564a-1233-44dd-a327-e9d5824300aa)

**Comment by scubamuc** [comment] 2023-10-06 11:43
> Also, what is the output of this address?
https://yourcloud.com/index.php/apps/richdocuments/settings/fonts.json

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/a8691a5e-a09d-49cc-ba70-cfd53cc1cee2)

**Comment by scubamuc** [comment] 2023-10-06 11:45
> @scubamuc Try again with the command with the "(" and ")", see my input & output:
grafik

???

**Comment by Pilzinsel64** [comment] 2023-10-06 11:47
Try the command I send above. As it is.
`( /sbin/ldconfig -p || scanelf -l ) | grep fontconfig`
And don't remove the "(" and ")", like you did: ~~`/sbin/ldconfig -p || scanelf -l | grep fontconfig`~~

**Comment by scubamuc** [comment] 2023-10-06 11:54
ahhh....
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/79e957ed-65b1-4129-a116-af9adb3d5bd5)

**Comment by scubamuc** [comment] 2023-10-06 11:56
nope... it keeps jumping back to "use your own server"

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/fe306b4e-91ed-423a-82f4-b6c81bc5520c)

**Comment by Pilzinsel64** [comment] 2023-10-06 11:58
Yea, that's fine now! Fontconfig is correctly installed.

But the picture you show me here doesn't look that nice...
But I can see that you you're cloud is reachable via https, right?

**Comment by Pilzinsel64** [comment] 2023-10-06 12:07
Sorry btw for for bothering you that much at the moment. 😞 It's just I'm in middle of the topic now and my brain has ideas and want to try that out.
Sadly, I can't reproduce the problem anymore myself, so I need others help. ;)

**Comment by scubamuc** [comment] 2023-10-06 12:18
@Pilzinsel64, hey no need to be sorry, it would be great if a solution is found.

**Comment by Pilzinsel64** [comment] 2023-10-06 13:48
@scubamuc If you want (and only if you want): Would it be possible to gain me access to your (or one or your) test-installation? I could then try myself if I can find the solution over the next several days when I have time.

**Comment by scubamuc** [comment] 2023-10-06 13:54
Hey @Pilzinsel64, sure no problem... do you need system access or instance access?
Drop me a mail and we'll get you sorted :-)

**Comment by scubamuc** [comment] 2023-10-08 09:15
See working configuration here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap
